language: python
sudo: true
dist: trusty
services:
  - postgresql
python:
  - 3.4
  - 3.5
before_install:
  - pip install requests
  - pip install PyYAML
  - pip install Jinja2
  - pip install coveralls
  - pip install psycopg2
  - gem install kwalify
  - sudo apt-get update -qq
  - sudo apt-get install -qq librpm-dev
before_script:
  - psql -c "CREATE DATABASE repology;" -U postgres
  - psql -c "CREATE USER repology WITH PASSWORD 'repology';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE repology TO repology";" -U postgres
script:
  # test buidling C utils
  - make

  # check yaml schemas
  - make check

  # run unit tests with coverage
  - coverage run --source=repology -m unittest discover

  # smoke tests, just try to run utils
  - ./repology-update.py --help
  - ./repology-dump.py --help

  # try to parse from testdata
  - ./repology-update.py -pdd -s testdata have_testdata

after_success:
  - coveralls
