language: python
sudo: true
dist: trusty
python:
  - 3.4
  - 3.5
before_install:
  - pip install requests
  - pip install PyYAML
  - pip install Jinja2
  - gem install kwalify
  - sudo apt-get update -qq
  - sudo apt-get install -qq librpm-dev
script:
  # Fetching from travis would be too heavy, so just
  # perform syntax check
  - make
  - make check
  - make test
  - ./repology-update.py --help
  - ./repology-report.py --help
  - ./repology-gensite.py --help
