language: python
sudo: true
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.5"
python:
  - 3.5
before_install:
  - pip install requests
  - pip install PyYAML
  - pip install Jinja2
  - pip install coveralls
  - pip install psycopg2
  - pip install flask
  - gem install kwalify
  - sudo apt-get update -qq
  - sudo apt-get install -qq librpm-dev
before_script:
  - psql -c "CREATE DATABASE repology_test;" -U postgres
  - psql -c "CREATE USER repology_test WITH PASSWORD 'repology_test';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE repology_test TO repology_test;" -U postgres
  - export REPOLOGY_CONFIG=repology-test.conf.default
script:
  # test buidling C utils
  - make

  # check yaml schemas
  - make check

  # fill database with test data
  - ./repology-update.py --parse --initdb --database

  # smoke test bit
  - ./repology-dump.py --help

  # run unit tests with coverage
  - coverage run --source=repology,repology-app -m unittest discover

after_success:
  - coveralls
