language: python
sudo: true
dist: trusty
python:
  - 3.4
  - 3.5
before_install:
  - pip install requests
  - pip install PyYAML
  - pip install Jinja2
  - pip install coveralls
  - pip install mysqlclient
  - gem install kwalify
  - sudo apt-get update -qq
  - sudo apt-get install -qq librpm-dev
script:
  # Fetching from travis would be too heavy, so just
  # perform syntax check
  - make
  - make check
  - coverage run --source=repology -m unittest discover
  - ./repology-update.py --help
  - ./repology-updatedb.py --help
  - ./repology-dump.py --help
  #- ./repology-report.py --help
  #- ./repology-gensite.py --help
after_success:
  - coveralls
