language: python
dist: bionic
sudo: required
addons:
  #postgresql: "10"  # 12 is needed, installed manually below
  apt:
    packages:
      - libyajl-dev  # for jsonslicer python module
      #- postgresql-server-dev-10  # for postgresql-libversion  # 12 is needed, installed manually below
      #- python3-rpm  # stock package is python3.5, useless for us
      - libnss3-dev  # for rpm
      - libnspr4-dev  # for rpm
      - libmagic-dev  # for rpm
      - libpopt-dev  # for rpm
      - libarchive-dev  # for rpm
      - libdb5.3-dev  # for rpm
env:
  global:
    - REPOLOGY_CONFIG=repology-test.conf.default
cache: pip
matrix:
  include:
    - python: 3.7
      env: COVERAGE=yes
    - python: 3.8
    - python: nightly
  allow_failures:
    - python: nightly
before_install:
  - sudo service postgresql stop
  - wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
  - sudo apt-get update
  - sudo apt-get install postgresql-12 postgresql-server-dev-12
  - sudo sed -i -e 's|#*port = .*|port = 5432|' /etc/postgresql/12/main/postgresql.conf
  - sudo sed -i -e 's|peer|trust|' /etc/postgresql/12/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart

  - export REAL_PYTHON=$(basename $(dirname $(python-config --configdir)))
  - |-
    mkdir -p dep-rpm
    (
        cd dep-rpm &&
        wget -qO- http://ftp.rpm.org/releases/rpm-4.14.x/rpm-4.14.2.1.tar.bz2 | tar -x -j -f- --strip-components 1 &&
        env PYTHON_CFLAGS="$(python-config --cflags)" PYTHON_LIBS="-L$(python-config --configdir) $(python-config --ldflags)" ./configure --enable-python --without-lua &&
        make &&
        sudo make install &&
        cp -Rfv "/usr/local/lib/${REAL_PYTHON}/site-packages/rpm" "${VIRTUAL_ENV}/lib/${REAL_PYTHON}/site-packages/"
    )
  - |-
    mkdir -p dep-libversion
    (
        cd dep-libversion &&
        wget -qO- https://github.com/repology/libversion/archive/master.tar.gz | tar -x -z -f- --strip-components 1 &&
        cmake . &&
        make &&
        sudo make install &&
        sudo ldconfig
    )
  - |-
    mkdir -p dep-postgresql-libversion
    (
        cd dep-postgresql-libversion &&
        wget -qO- https://github.com/repology/postgresql-libversion/archive/master.tar.gz | tar -x -z -f- --strip-components 1 &&
        make &&
        sudo make install
    )
  - pip install -r requirements-dev.txt
  - pip install codecov
before_script:
  - git clone --depth=1 https://github.com/repology/repology-rules.git rules.d
  - sudo -u postgres psql -c "CREATE DATABASE repology_test;"
  - sudo -u postgres psql -c "CREATE USER repology_test WITH PASSWORD 'repology_test'"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE repology_test TO repology_test"
  - sudo -u postgres psql -d repology_test -c "CREATE EXTENSION IF NOT EXISTS pg_trgm"
  - sudo -u postgres psql -d repology_test -c "CREATE EXTENSION IF NOT EXISTS libversion"
script:
  # check yaml schemas
  - make check

  # check python syntax
  - make flake8

  # check python types
  - make mypy

  # fill database with test data
  - ./repology-update.py --initdb --parse --database --postupdate

  # smoke test bits
  - ./repology-dump.py --help
  - ./repology-gensitemap.py --main > sitemap-main.xml
  - ./repology-gensitemap.py --metapackages > sitemap-metapackages.xml

  # run unit tests with coverage
  - coverage run --source=repology --omit="repology/test/*,repology/fetchers/*" -m unittest discover

after_success:
  - if [ -n "$COVERAGE" ]; then codecov; fi
