language: python
sudo: true
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.5"
python:
  - 3.5
before_install:
  - pip install requests
  - pip install PyYAML
  - pip install Jinja2
  - pip install coveralls
  - pip install psycopg2
  - pip install flask
  - pip install pytidylib # XXX: proper html validation needs tidy-html5
  - gem install kwalify
  - pip install rubymarshal
  - pip install flake8
  - pip install flake8-builtins
  - pip install flake8-import-order
  - sudo apt-get update -qq
  - sudo apt-get install -qq librpm-dev
  - wget -qO- https://github.com/repology/libversion/archive/1.0.0.tar.gz | tar -xzf- && ( cd libversion-1.0.0 && cmake . && make && sudo make install )
before_script:
  - psql -c "CREATE DATABASE repology_test;" -U postgres
  - psql -c "CREATE USER repology_test WITH PASSWORD 'repology_test';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE repology_test TO repology_test;" -U postgres
  - export REPOLOGY_CONFIG=repology-test.conf.default
script:
  # test buidling C utils
  - make

  # check yaml schemas
  - make check

  # check python syntax
  - make flake8

  # fill database with test data
  - ./repology-update.py --parse --initdb --database

  # smoke test bit
  - ./repology-dump.py --help

  # run unit tests with coverage
  - coverage run --source="repology,repology-app" --omit="repology/fetcher/*" -m unittest discover

after_success:
  - coveralls
