###########################################################################
# Conda
###########################################################################
- name: conda_forge
  type: repository
  desc: conda-forge
  family: conda
  minpackages: 1
  sources:
    - name: channeldata.json
      fetcher:
        class: FileFetcher
        url: 'https://conda.anaconda.org/conda-forge/channeldata.json'
      parser:
        class: CondaChanneldataJsonParser
  repolinks:
    - desc: conda-forge home
      url: https://conda-forge.org/
  groups: [ all, conda ]

- name: bioconda
  type: repository
  desc: Bioconda
  family: conda
  minpackages: 1
  sources:
    - name: channeldata.json
      fetcher:
        class: FileFetcher
        url: 'https://conda.anaconda.org/bioconda/channeldata.json'
      parser:
        class: CondaChanneldataJsonParser
  repolinks:
    - desc: Bioconda home
      url: https://bioconda.github.io/
  groups: [ all, conda ]
